var config = {};

config.sean = {
   host: 'lenovo', //run in local
   port: '3556',
   mysql: {
      host: "3.1.225.162",
      port: "3306",
      database: "",
      user: "remote",
      password: ""
   },
   is_staging: false,
   set_question :{
      1: {
         q1: "Komisi DPR-RI yang banyak berhubungan dengan Departemen keuangan adalah . . .",
         a1 : "Komisi III",
         f1 : "Komisi Badan Musyawarah",
         q2: "Apa sebutan untuk proses pemilihan Perdana Menteri yang melibatkan perwakilan rakyat?",
         a2 : "House of Parliaments",
         f2 : "Parlementer",
         q3 : "Gunung tertinggi di dunia",
         a3: "Mount Everest",
         f3: "Cikurai",
         q4 : "Siapa nama presiden Amerika Serikat yang tertembak di teater Ford, Washington, Amerika Serikat pada 14 April 1865?",
         a4: "abraham Lincoln",
         f4: "John O' Corner"
      },
      2: {
         a1: "empat",
         f1: "2",
         q1: "Umar Wirahadikusuma adalah wakil presiden Indonesia ke-",
         a2: "Goliath",
         f2: "Titanus Gilgateus",
         q2: "Apa nama jenis kumbang terbesar di dunia?",
         a3: "Abate",
         f3: "Air sabun",
         q3: "Apa nama obat untuk membunuh jentik-jentik di dalam air?",
         a4: "peng Ekspor Minyak",
         f4: "Iran, Irak, Kuwait, Arab Saudi, dan Venezuela",
         q4: "OPEC adalah organisasi internasional yang anggotanya terdiri dari negara-negara..."
   
      },
      3 : {
        a1: "Benito Mussolini",
        f1: "Sento Mozali",
        q1: "Which Fascist leader was called \"Il Duce\" by his followers?" , 
        a2: "golf",
        f2: "football",
        q2: "Scotland is the birthplace of what ball and stick sport?",   
        a3: "Sir Edmund Hillary",
        f3: "King Arthur",
        q3: "Who was the first person to climb Mount Everest?",     
        a4: "Saint Augustine, Florida",
        f4: "albani, europa",
        q4: "What is the oldest city in the United States?"
      },
      4:{
         a1: "Nawaz Sharif",
        f1: "Fulqabi Zoli",
        q1: "Who was sworn in for a second term as minister of Pakistan in 1993?", 
        a2: "lebensraum",
        f2: "Weltanschaung",
        q2: "The German Invasion of the Soviet Union was brought about in order to fulfill the policy of",
        a3: "The battle of britain",
        f3: "The beginning of operation Barbossa",
        q3: "Adler Tag refers to",
        a4: "Ohka",
        f4: "Tora",
        q4: "The Japanese rocket-powered suicide planes launched from Beddy bombers were known as"
      },
      5: {
         a1: "Sturmgewehr 44",
         f1: "AK-47",
         q1: "The first mass produced assault rifle was known as"  ,
         a2: "Uranus",
         f2: "Zitadelle",
         q2: "Zhukov's encirclement of the German 6th Army was known as operation ..." , 
         a3: "El alamein",
         f3: "Kasserine pass",
         q3: "The most significant battle of the African campaign was known as",
         a4: "Ploesti",
         f4: "Stalinggrad",
         q4: "The Axis oilfields at ________ were repeatedly attacked by Allied bombers"
      },
      6:{
         a1: "Liberty",
        f1: "Enterprise",
        q1: "The _______ ships were a class of mass-produced wooden American merchant ship.",    
        a2: "Norden",
        f2: "Revi",
        q2: "The _______ bombsight was a great leap forward in level-bombing technology", 
        a3: "Erich hartmann",
        f3: "Adolp galland worrer",
        q3: "Who was the highest scoring aerial ace of WWII?",
        a4: "Finland",
        f4: "United states",
        q4: "The most prolific sniper of the Second World War, with more than 500 'kills', came from which country?",
      },
      7 : {
         a1: "Tim robbins",
         f1: "Josh hartnett",
         q1: "In the 1994 movie The Shawshank Redemption one of the lead male roles was played by ?",   
         a2: "James stewart",
         f2: "James Caan",
         q2: "In the 1954 Hitchcock classic Rear Window, who played the lead actor ?",  
         a3: "Andromeda",
         f3: "Cepheus",
         q3: "Who Was Chained To Rock As Prey For Monster, Rescued By Perseus?",     
         a4: "Jivika",
         f4: "Trozsavka",
         q4: "Who Was The Personal Physician Of Buddha"
      },
      8 : {
         a1: "Ghandharvam",
         f1: "Diablo",
         q1: "What Was The Ancient Name Of Music?",   
         a2: "Herod antipas",
         f2: "Bin irad",
         q2: "Who murders John the Baptist?",  
         a3: "The god of sleep",
         f3: "God of music",
         q3: "Who Is The Hypnos Of Greek Mythology?",   
         a4: "Mudrarakshahsa",
         f4: "Ritusamhara",
         q4: "Which among the following Kavya of Sanskrit, deal with court intrigues & access to power of Chandragupta Maurya?"
      },
      9: {
         a1: "Freya",
        f1: "Lanaya",
        q1: "In Norse Mythology Who Is The Goddess Of Night And Love?" ,
        a2: "Philosophy",
        f2: "Social life",
        q2: "Upnishads are books on :",  
        a3: "Shield",
        f3: "Power",
        q3: "In every battle you will need faith as your ______ to stop the fiery arrows aimed at you by Satan", 
        a4: "The beatitudes",
        f4: "Anglicized",
        q4: "What is another name for the Sermon on the Mount?"
      },
      10: {
         a1: "Aeolus",
        f1: "Pazuzu",
        q1: "Who Was Ruler Of Winds In Greek Mythology?" ,
        a2: "Vishnu",
        f2: "Indra",
        q2: "Who was the main male God worshipped by Indus people?",  
        a3: "Holy book of sikhs",
        f3: "American basketball player",
        q3: "What Is The Granth Sahib?",   
        a4: "Mount Olives",
        f4: "Gethsemane",
        q4: "From Where Did Jesus Christ Ascend To Heaven?"
      },
      11 : {
         a1: "Ararat",
        f1: "Tevat",
        q1: "Where Did Noah’s Ark Come To Rest Afer The Flood?",
     
        a2: "Locusts",
        f2: "Scorpio",
        q2: "What type of insect did John the Baptist eat in the desert? ",
     
        a3: "Jason",
        f3: "Sebastian",
        q3: "In Greek Mythology, Which Prince Led The Argoniuts To Win The Golden Fleece With The Aid Of Medea?",
     
        a4: "Harsha",
        f4: "Skandagupta",
        q4: "Who was the last Hindu emperor of northern India?"
      },
      12: {
         a1: "rhydon",
        f1: "mew",
        q1: "What is the first pokemon?",   
        a2: "golden girdle",
        f2: "twoedged sword",
        q2: "And in the midst of the seven candlesticks one like unto the Son of man, clothed with a garment down to the foot, and girt about the paps with a ______ ",     
        a3: "warsaw poland",
        f3: "Naples, Italy",
        q3: "Which of the following cities was the first to open a public library?",   
        a4: "Caspian",
        f4: "dead",
        q4: "Caviar is the processed eggs of sturgeon that live in the ______ Sea"
      },
      13 : {
         a1: "august 1961",
         f1: "1953 18 june",
         q1: "When did East Germany begin building the Berlin Wall?",    
         a2: "synagogue",
         f2: "spirit",
         q2: "Behold, I will make them of the ______ of Satan, which say they are Jews, and are not, but do lie; behold, I will make them to come and worship before thy feet, and to know that I have loved thee.",  
         a3: "san marino",
         f3: "austria",
         q3: "Which is the oldest republic in the world?",  
         a4: "nimes",
         f4: "le havre",
         q4: "The word 'denim' comes from the French town of...:"
      },
      14 : {
         
        a1: "38 minutes",
        f1: "57 minutes",
        q1: "The shortest war on record lasted ...?",
        a2: "Rio grande",
        f2: "river",
        q2: "In Spring 2001, the _____ stopped flowing into the Gulf of Mexico for the first time in history.",
        a3: "Rhinoceros Beetle",
        f3: "ant",
        q3: "The ______ can carry up to 850 times its own body weight",  
        a4: "alakazam",
        f4: "dragonite",
        q4: "What pokemon has an IQ of 5000?"
      },
      15 : {
         a1: "water",
         f1: "grass",
         q1: "What is the most commen type of pokemon?",     
         a2: "oysters",
         f2: "lumpsucker",
         q2: "What animals are pearls found in?",   
         a3: "6",
         f3: "121",
         q3: "How many Regions are in the pokemon game?", 
         a4: "Knee cap",
         f4: "T-bone",
         q4: "Which bone are babies born without?"
      },
      16: {
         a1: "Rosebud",
         f1: "Oh wow",
         q1: "What are the dying words of Charles Foster Kane in Citizen Kane?",   
         a2: "anne bancroft",
         f2: "emmerson nogueira",
         q2: "Who played Mrs. Robinson in The Graduate?",  
         a3: "nakatomi plaza",
         f3: "burj khalifa",
         q3: "What’s the name of the skyscraper in Die Hard?", 
         a4: "the last house on the left",
         f4: "mama",
         q4: "What shocking Wes Craven horror movie carried the marketing tagline, 'To avoid fainting, keep repeating, ‘It’s only a movie…'?"
      },
      17 : {
         a1: "horse",
        f1: "bird",
        q1: "The head of what kind of animal is front-and-center in an infamous scene from The Godfather?",
      
        a2: "griffith observatory",
        f2: "purgatory",
        q2: "What famous L.A. landmark is heavily featured in Rebel Without a Cause?",
     
        a3: "james whale",
        f3: "robert b weide",
        q3: "Who directed Boris Karloff in the classics Frankenstein and Bride of Frankenstein?",
      
        a4: "kathleen turner",
        f4: "eva bella",
        q4: "Who voiced the sultry Jessica Rabbit in Who’s Afraid of Roger Rabbit? "
      },
      18 : {
         a1: "napalm",
        f1: "rain",
        q1: "In Apocalypse Now, Robert Duvall says, 'I love the smell of _____ in the morning.'",
      
        a2: "The Passion of the Christ",
        f2: "joker",
        q2: "What is the highest-grossing foreign-language film at the U.S. box office?",
      
        a3: "sylvester stallone",
        f3: "shannon",
        q3: "Who wrote the screenplay for Rocky?",
     
        a4: "USCSS nostromo",
        f4: "fireball xl5",
        q4: "What is the name of the spaceship in Alien?"
      },
      19 : {
         a1: "twttr",
         f1: "blue bird",
         q1: "What was Twitter’s original name?",
      
         a2: "Red/green",
         f2: "Pokemon Gen 1",
         q2: "What where the first pokemon games called?",
       
         a3: "marie curie",
         f3: "stella oliver",
         q3: "Who was the first woman to win a Nobel Prize (in 1903)?",
       
         a4: "jupiter",
         f4: "pluto",
         q4: "Which planet has the most gravity?"
      },
      20 : {
         a1: "bavarian motor works",
         f1: "Babbling Mechanical Wench",
         q1: "What does BMW stand for (in English)?",     
         a2: "chickpeas",
         f2: "garlic",
         q2: "What’s the primary ingredient in hummus?",
         a3: "game freak",
         f3: "shagirai miamoto",
         q3: "This is the last question and it is hard: WHO MADE POKEMON!!!",   
         a4: "canis lupus",
         f4: "loxodonta",
         q4: "What’s the scientific name of a wolf?"
      },
      21 : {
         a1: "jenny",
        f1: "wonky donkey",
        q1: "What is a female donkey called?",
        a2: "giraffe",
        f2: "bee",
        q2: "Which mammal has no vocal cords?",
        a3: "The Nile",
        f3: "Jordan river",
        q3: "What is the name of the world’s longest river?",
        a4: "Karl benz",
        f4: "karl bountine",
        q4: "Who is often credited with creating the world’s first car?"
      },
      22 : {
         a1: "Reticulates",
        f1: "Gornohamea",
        q1: "Indonesia adalah Tempat ditemukannya ular terpanjang di dunia yaitu, Python ... sepanjang 10 meter di Sulawesi",   
        a2: "Aurora borealis",
        f2: "Meteorolit",
        q2: "Pada Sept1909 malam hari, warga Jakarta beruntung menyaksikan ... di langit yg biasanya hanya di kutub ( Prof. Truls L Hansen)",  
        a3: "Bromelain",
        f3: "Cairan",
        q3: ".... yang terkandung dalam Nanas bila dikonsumsi berlebihan bagi wanita hamil bisa memicu kontraksi dini bahkan keguguran",  
        a4: "Tom cruise day",
        f4: "Kemerdekaan Jepang",
        q4: "Secara resmi setiap tanggal 6 Oktober di Jepang merayakan ...."
      },
      23 : {
         a1: "suramadu",
         f1: "Grand danyang",
         q1: "Jembatan ... adalah jembatan terpanjang di Asia Tenggara (5438 m).",   
         a2: "bawang putih",
         f2: "permen karet",
         q2: "Orang sherpa di Nepal menganjurkan orang memakan .... utk mencegah dan mengobati rasa tidak nyaman yg disebabkan ketinggian gunung",    
         a3: "2631",
         f3: "4869",
         q3: "Teka-teki silang terbesar yang pernah diterbitkan memiliki .... pertanyaan mendatar dan 2922 pertanyaan menurun.",   
         a4: "metana",
         f4: "peroksida",
         q4: "Kecoa kentut setiap 15 menit dan terus mengeluarkan ... selama 18 jam setelah kematian"
      },
      24 : {
         a1: "Alexandre eiffel",
         f1: "Eifel Lope",
         q1: "Menara Eiffel dibangun oleh ...., dan sebagian besar biayanya ditanggung oleh dia",
         a2: "kecoa",
         f2: "burger",
         q2: "Ken Edwards seorang pria asal Inggris memegang rekor Guinness untuk makan 36 ... dalam 1 menit",
         a3: "angin ribut",
         f3: "PLTA",
         q3: "Energi yang dihasilkan oleh ... selama 10 menit lebih besar dibandingkan energi dari bom saat perang", 
         a4: "Idiot",
         f4: "dalam",
         q4: "Kata “depp” dalam bahasa Jerman artinya “ ... ”"
      },
      25 : {
         a1: "lampung",
         f1: "Parahyangan",
         q1: "Menghisap rokok sambil makan cokelat dapat membunuh racun yang terdapat pada rokok tersebut. [penelitian kedokteran di Universitas .....]",     
         a2: "badan yang lebih tinggi",
         f2: "uang",
         q2: "Kebanyakan orang lebih percaya terhadap kemampuan kepemimpinan seseorang jika orang itu memiliki .....",     
         a3: "gendut",
         f3: "autis",
         q3: "Kebiasaan sibuk memotret dan mengunggah foto makanan di sosial media, beresiko seseorang menjadi ? [Dr. Valerie Taylor]",    
         a4: "oksigen",
         f4: "clorin",
         q4: "Pulau Giliyang di Sumenep, Jawa Timur disebut sbg pulau “Awet Muda” karena pulau ini memiliki kandungan .... terbaik di dunia"
      },
      26 : {
         a1: "wifman",
        f1: "eve",
        q1: "Istilah WOMAN berasal dari bahasa inggris zaman pertengahan ' ... ' yang artinya istri seorang laki laki",    
        a2: "walt disney",
        f2: "marvel",
        q2: "istilah vagina pertama kali digunakan dalam film produksi ...",
        a3: "keringan gladiator",
        f3: "bunga serm abadi",
        q3: "Kaum wanita pada zaman romawi kuno menggunakan ... untuk mempercantik diri", 
        a4: "Sara Breedlove",
        f4: "Kettleen William",
        q4: "wanita terkaya pertama di amerika adalah .."
      },
      27 : {
         a1: "Morologi ",
         f1: "qiqizologi",
         q1: "..... adalah studi tentang percakapan konyol", 
         a2: "mendayung",
         f2: "bersepeda",
         q2: "Tertawa sebanyak 100 kali setara dengan .... selama 10 menit",
         a3: "Musik heavy metal",
         f3: "sayuran",
         q3: "Studi menunjukkan penggemar ...... ternyata lebih bisa meredam emosi negatif dan lebih ekspresif",    
         a4: "gigi ompong",
         f4: "kempot",
         q4: "Di Cape Town, Afrika Selatan, remaja laki-laki yang memiliki ..... dianggap tampan"
      },
      28 : {
         a1: "pencuri",
        f1: "penyair",
        q1: "Kata “Mouse” (tikus) berasal dari turunan Bahasa Sansekerta “Mus” yang berarti .....",
      
        a2: "bersolek",
        f2: "operasi plastik",
        q2: "Menurut riset pasar global Euromonitor International, pria Korea adalah pria yang paling suka ... dari pria lain di dunia.",
     
        a3: "hari Rabu pukul 15.30",
        f3: "pagi hari",
        q3: "Wanita merasa diri mereka terlihat paling jelek dan terlihat lebih tua pada ....",
     
        a4: "Perempuan berbulu",
        f4: "orang gila",
        q4: "Nama “Gorila” berasal dari kata Yunani “Gorillai” yang berarti ....."
      },
      29 : {
         a1: "stupid",
         f1: "nasi",
         q1: "Selama abad ke-13, kata “nice” sebenarnya berarti ....",  
         a2: "jomblo",
         f2: "wanita",
         q2: "49% dari pemilik Smartphone adalah .." ,
         a3: "susu kucing",
         f3: "susu manusia",
         q3: "Gazzarella adalah keju mozzarella yang terbuat dari ...." , 
         a4: "Bugs bunny",
         f4: "ronald bebek",
         q4: "Karakter kartun ..... diberi pangkat kehormatan sersan-mayor di Korps Marinir AS pada akhir Perang Dunia II"
      },
      30 : {
         a1: "dopamin ",
        f1: "estrogen",
        q1: "Ketika kita sedang jatuh cinta, otak akan memproduksi ..... ekstra, bahan kimia yang membuat seseorang menjadi gembira berlebihan.",
    
        a2: "Mwahahaha",
        f2: "stuckacapapa",
        q2: "..... telah ditambahkan ke Kamus Inggris Oxford",
    
        a3: "true",
        f3: "false",
        q3: "Menurut penelitian, pria cenderung menurunkan volume suaranya ketika ia berbicara dg seseorang yg ia cintai, sementara perempuan sebaliknya",
        a4: "Tanduk badak",
        f4: "boba",
        q4: ".... terbuat dari keratin"
      },
      31 : {
         a1: "Lobster",
         f1: "orang jahat",
         q1: ".... memiliki darah biru",
      
         a2: "Obat",
         f2: "bahan bangunan",
         q2: "Kecap sebelumnya dijual sebagai ...",
     
         a3: "send dan tembaga",
         f3: "protein",
         q3: "Orang yang cerdas memiliki kadar .... di rambut mereka",
         a4: "Pohon kelapa",
         f4: "kecelakaan",
         q4: ".... membunuh 150 orang tiap tahun, lebih banyak daripada hiu"
      },
      32 : {
         a1: "anggur",
        f1: "popcorn",
        q1: ".... dapat meledak jika dimasukkan ke dalam microwave",   
        a2: "kiwi",
        f2: "Jeruk",
        q2: ".... ditetapkan sebagai buah kebangsaan di Cina", 
        a3: "pisang",
        f3: "tulang ikan",
        q3: "Riset membuktikan, memakan ..... bisa menambah daya ingat",
        a4: "Llanfairpwllgwyngyllgogerychwyrndrobwlll",
        f4: "KwazakwazakKazkkzkkk",
        q4: "Tahukah anda? ..... , adalah nama sebuah desa di Wales Utara, Inggris. Sulit dibaca bukan?"
      },
      33: { a1: "20%",
         f1: "3%",
         q1: "The Amazon Rainforest Produces ___ of the World’s Oxygen",   
         a2: "3x -4y+32 = 0",
         f2: "Tidak ada persamaan garis singgung",
         q2: "Diketahui sebuah lingkaran melalui titik 0(0, 0), A(0, 8), dan B(6, 0). Persamaan garis singgung pada lingkaran tersebut di titik A adalah ….", 
         a3: "The Mariana Trench",
         f3: "Lake Michigan",
         q3: " ... is the Deepest Point on Earth Located in the Pacific Ocean, it plunges about 10,984 meters (36,037 feet). If Mount Everest were placed inside, its peak would still be over a mile underwater.",
         a4: "The Great Wall",
         f4: "The Burj Khalifak",
         q4: "the World’s Largest Man-Made Structure, Stretching over 21,000 kilometers"        
      },
      34: {
         a1: "Tulang Sanggurdi",
         f1: "Humerus",
         q1: "the smallest bone in the human body",   
         a2: "Lukas",
         f2: "Wahyu",
         q2: "What is the longest book in the New Testament", 
         a3: "Jeremiah",
         f3: "daniel",
         q3: "Which prophet is known as the 'weeping prophet' ?",
         a4: "Shalmaneser V",
         f4: "Herodes VI",
         q4: "Siapakah nama raja yang menghancurkan kerajaan utara Israel dan membawa rakyatnya ke pembuangan"  
      },
      35: {
         a1: "Oymyakon",
         f1: "Sitenka",
         q1: "What is the name of the village in Russia that holds the record for the coldest temperature ever recorded in a permanently inhabited place on Earth",   
         a2: "quahog clam",
         f2: "Black Shark",
         q2: "Which animal is known to have the longest confirmed lifespan", 
         a3: "93 billion light-years",
         f3: "2134 Quart Light Years",
         q3: "What is the size of the observable universe, in light-years",
         a4: "Papua Nugini",
         f4: "Meksiko",
         q4: "What is the most linguistically diverse country in the world"
      },
      36: {
         a1: "Penaklukan",
         f1: "Kelaparan",
         q1: "Ada empat penunggang kuda yang disebutkan dalam Wahyu 6, apa simbol untuk kuda putih",   
         a2: "Maher-syalal Hash-baz",
         f2: "Sisera Herib",
         q2: "Siapakah nama anak nabi Yesaya yang memiliki arti 'cepatlah merampas, segera ambil jarahan'?", 
         a3: "Manasye",
         f3: "Lord Samuel",
         q3: "Siapakah nama raja Yehuda yang menjadi raja pada usia 12 tahun?",
         a4: "Yizreel",
         f4: "Lo-Ammi",
         q4: "Siapakah nama putra Hosea yang melambangkan penghakiman Allah terhadap Israel"
      },
      37: {
         a1: "Marmut",
         f1: "Anjing",
         q1: "Di Swiss, ilegal memelihara hanya satu ekor hewan ini karena mereka makhluk sosial:",
         a2: "38 Menit",
         f2: "2 Hari",
         q2: "Perang tersingkat dalam sejarah (Inggris vs Zanzibar) berlangsung selama...",
         a3: "Pisang",
         f3: "Apel",
         q3: "Secara botani, stroberi bukanlah buah beri, melainkan buah ini yang justru diklasifikasikan sebagai beri:",
         a4: "Merah muda",
         f4: "Biru",
         q4: "Susu kuda nil memiliki warna yang unik, yaitu..."
      },
      38: {
         a1: "Wombat",
         f1: "Beruang Koala",
         q1: "Hewan ini memiliki kotoran yang berbentuk kubus untuk mencegahnya menggelinding:",
         a2: "Beruang Kutub",
         f2: "Bunglon",
         q2: "Bulu hewan ini sebenarnya transparan (bening), bukan putih:",
         a3: "Gurita",
         f3: "Cumi-cumi",
         q3: "Hewan laut ini memiliki tiga jantung dan darah berwarna biru:",
         a4: "Kelelawar",
         f4: "Burung Unta",
         q4: "Mamalia satu-satunya yang secara alami dapat terbang adalah..."
      },
      39: {
         a1: "Ubur-ubur",
         f1: "Bintang Laut",
         q1: "Turritopsis dohrnii dikenal sebagai satu-satunya makhluk hidup yang 'abadi'. Hewan apakah itu?",
         a2: "Bumi",
         f2: "Venus",
         q2: "Satu-satunya planet di tata surya kita yang tidak dinamai dari dewa-dewi Yunani atau Romawi adalah...",
         a3: "Madu",
         f3: "Garam",
         q3: "Makanan ini tidak pernah basi dan dapat dimakan meski sudah berusia ribuan tahun:",
         a4: "Eropa",
         f4: "Afrika",
         q4: "Satu-satunya benua di dunia yang tidak memiliki padang pasir adalah..."
      },
      40: {
         a1: "Mengecap",
         f1: "Mendengar",
         q1: "Kupu-kupu menggunakan kaki mereka untuk...",
         a2: "Venus",
         f2: "Mars",
         q2: "Planet ini berputar berlawanan arah jarum jam dibandingkan dengan sebagian besar planet lain:",
         a3: "Kanguru",
         f3: "Burung Emu",
         q3: "Hewan ini tidak bisa berjalan mundur, sehingga menjadi simbol kemajuan di lambang negara Australia:",
         a4: "Menara Eiffel",
         f4: "Patung Liberty",
         q4: "Bangunan ini dapat bertambah tinggi sekitar 15 cm di musim panas karena pemuaian besi:"
      },
      41: {
         a1: "Gigi",
         f1: "jantung",
         q1: "Selain sidik jari, bagian tubuh manusia yang mana lagi yang tidak pernah sama persis pada dua orang berbeda?",
         a2: "Mata",
         f2: "Hidung",
         q2: "Organ tubuh manusia yang tetap berukuran sama dari sejak lahir sampai mati adalah...",
         a3: "Paus Biru",
         f3: "Gajah",
         q3: "Hewan yang memiliki jantung sebesar mobil adalah...",
         a4: "Gajah",
         f4: "Badak",
         q4: "Satu-satunya mamalia yang tidak bisa melompat adalah..."
      },
      42: {
         a1: "Nyamuk",
         f1: "Ular",
         q1: "Hewan yang bertanggung jawab atas kematian manusia terbanyak setiap tahunnya adalah...",
         a2: "Burung Hantu",
         f2: "Elang",
         q2: "Burung satu-satunya yang bisa melihat warna biru adalah...",
         a3: "Vatikan",
         f3: "Monako",
         q3: "Negara terkecil di dunia adalah...",
         a4: "Rusia",
         f4: "China",
         q4: "Negara dengan wilayah terbesar di dunia adalah..."
      },
      43: {
         a1: "Pluto",
         f1: "Mars",
         q1: "Nama tokoh Disney Mickey Mouse sebenarnya terinspirasi dari planet apa?",
         a2: "Kucing",
         f2: "Anjing",
         q2: "Hewan apa yang menjadi walikota di kota Talkeetna, Alaska, selama 20 tahun?",
         a3: "Burung Kolibri",
         f3: "Burung Hantu",
         q3: "Satu-satunya burung yang dapat terbang mundur adalah...",
         a4: "Alpukat",
         f4: "Mangga",
         q4: "Buah yang juga dikenal dengan sebutan 'pir buaya' adalah..."
      },
      44: {
         a1: "Jerapah",
         f1: "Zebra",
         q1: "Hewan yang memiliki lidah berwarna hitam kebiruan untuk melindunginya dari sengatan matahari adalah...",
         a2: "Air",
         f2: "Minyak",
         q2: "Komponen utama penyusun awan adalah...",
         a3: "Hiu",
         f3: "Buaya",
         q3: "Hewan purba yang sudah ada lebih lama daripada pohon adalah...",
         a4: "Flamingo",
         f4: "Bangau",
         q4: "Burung ini lahir dengan bulu berwarna abu-abu, namun menjadi merah muda karena makanannya (udang):"
      },
      45: {
         a1: "Monalisa",
         f1: "Starry Night",
         q1: "Lukisan terkenal yang tidak memiliki alis karena tren kecantikan masa itu adalah...",
         a2: "Kuda Laut",
         f2: "Ikan Pari",
         q2: "Satu-satunya spesies hewan dimana jantan yang mengandung dan melahirkan adalah...",
         a3: "Semut",
         f3: "Lebah",
         q3: "Serangga ini tidak pernah tidur sepanjang hidupnya:",
         a4: "Antartika",
         f4: "Gurun Sahara",
         q4: "Tempat terkering di Bumi (Lembah Kering McMurdo) sebenarnya terletak di benua..."
      },
      46: {
         a1: "Oxford",
         f1: "Cambridge",
         q1: "Universitas mana yang usianya lebih tua dari Kekaisaran Aztec?",
         a2: "Unta",
         f2: "Kuda",
         q2: "Hewan ini memiliki tiga kelopak mata untuk melindungi matanya dari pasir tertiup:",
         a3: "Bambu",
         f3: "Pohon Pisang",
         q3: "Tumbuhan dengan pertumbuhan tercepat di dunia, yang bisa tumbuh hingga 90 cm sehari, adalah...",
         a4: "Cokelat",
         f4: "Vanila",
         q4: "Rasa asli makanan suku Aztec yang digunakan sebagai mata uang sebelum invasi Spanyol adalah..."
      },
      47: {
         a1: "Tikus",
         f1: "Kucing",
         q1: "Hewan apa yang tertawa (mengeluarkan suara frekuensi tinggi) saat digelitik?",
         a2: "Merah",
         f2: "Hijau",
         q2: "Warna apa yang sebenarnya tidak bisa dilihat oleh banteng (karena mereka buta warna)?",
         a3: "Lidah",
         f3: "Jari Manis",
         q3: "Otot terkuat di tubuh manusia (berdasarkan proporsi ukurannya) adalah...",
         a4: "Tomat",
         f4: "Mentimun",
         q4: "Sayuran yang sebenarnya secara botani adalah buah, dan sempat memicu perdebatan di Mahkamah Agung AS:"
      },
      48: {
         a1: "Venus",
         f1: "Mars",
         q1: "Planet di mana satu hari lebih lama daripada satu tahunnya adalah...",
         a2: "Platypus",
         f2: "Echidna",
         q2: "Hewan mamalia ini bertelur dan menyusui tanpa puting, melainkan mengeluarkan susu melalui perutnya:",
         a3: "Bir",
         f3: "Wine",
         q3: "Minuman yang resep tertuanya ditemukan di tablet tanah liat Sumeria kuno adalah...",
         a4: "Tulang Paha",
         f4: "Tulang Belakang",
         q4: "Tulang terpanjang dan terkuat dalam tubuh manusia adalah..."
      },
      49: {
         a1: "Nanas",
         f1: "Semangka",
         q1: "Buah ini mengandung enzim Bromelain yang memecah protein daging Anda saat Anda memakannya:",
         a2: "Katak Kayu",
         f2: "Bunglon",
         q2: "Hewan yang bisa membekukan dirinya selama musim dingin dan mencair kembali di musim semi adalah...",
         a3: "Burung Unta",
         f3: "Jerapah",
         q3: "Mata hewan ini lebih besar daripada otaknya:",
         a4: "10 Persen",
         f4: "1 Persen",
         q4: "Berapa persen dari populasi dunia yang kidal (menggunakan tangan kiri)?"
      },
      50: {
         a1: "Lebah",
         f1: "Lalat",
         q1: "Serangga yang dapat mengenali wajah manusia layaknya kita mengenali satu sama lain adalah...",
         a2: "Kungkang",
         f2: "Koala",
         q2: "Hewan yang saking lambatnya, lumut dan alga bisa tumbuh di bulunya adalah...",
         a3: "Catur",
         f3: "Monopoli",
         q3: "Permainan papan mana yang memiliki lebih banyak kemungkinan permainan daripada jumlah atom di alam semesta yang dapat diamati?",
         a4: "Sidik Lidah",
         f4: "Sidik Bibir",
         q4: "Selain sidik jari, manusia juga memiliki 'sidik' unik pada bagian tubuh..."
      },
      51: {
         a1: "Kaca",
         f1: "Plastik",
         q1: "Material buatan manusia yang membutuhkan waktu paling lama terurai di alam bebas (bisa lebih dari 1 juta tahun):",
         a2: "Kaki",
         f2: "Air Liur",
         q2: "Anjing tidak berkeringat melalui seluruh kulit mereka, melainkan melalui...",
         a3: "Emas",
         f3: "Perak",
         q3: "Logam mulia yang dapat dimakan dan sering ditambahkan ke hidangan penutup mahal adalah...",
         a4: "Ayam",
         f4: "Sapi",
         q4: "Hewan darat yang memiliki populasi terbanyak di bumi (melebihi jumlah manusia) adalah..."
      },
      52: {
         a1: "Awan",
         f1: "Salju",
         q1: "Fenomena cuaca ini sebenarnya sangat berat (satu gumpalan bisa seberat 100 gajah) meskipun terlihat ringan:",
         a2: "Kecoa",
         f2: "Tikus",
         q2: "Serangga ini bisa hidup selama berminggu-minggu tanpa kepala sebelum akhirnya mati kelaparan:",
         a3: "Beruang Kutub",
         f3: "Pinguin",
         q3: "Hewan apa yang memiliki kulit hitam di balik bulunya yang tampak seputih salju?",
         a4: "Bunglon",
         f4: "Katak Beracun",
         q4: "Hewan yang dapat memutar kedua matanya secara independen ke arah yang berbeda adalah..."
      },
      53: {
         a1: "Jerapah",
         f1: "Paus",
         q1: "Meskipun lehernya sangat panjang, hewan ini memiliki jumlah tulang leher sama dengan manusia (7 tulang):",
         a2: "Wortel",
         f2: "Kentang",
         q2: "Sayuran yang pada awalnya berwarna ungu atau kuning sebelum dibiakkan menjadi oranye di Belanda adalah...",
         a3: "Kacang Tanah",
         f3: "Kacang Almond",
         q3: "Kacang ini bisa digunakan sebagai bahan dasar dinamit (nitrogliserin):",
         a4: "Bawang Merah",
         f4: "Cabai",
         q4: "Tanaman ini bisa membuat Anda menangis saat dipotong karena melepaskan gas asam sulfenat:"
      },
      54: {
         a1: "Lumba-lumba",
         f1: "Hiu",
         q1: "Hewan air yang tidur dengan satu mata terbuka dan setengah otaknya tetap sadar untuk tetap bernapas adalah...",
         a2: "Pinguin",
         f2: "Burung Unta",
         q2: "Satu-satunya burung yang bisa berenang namun tidak bisa terbang adalah...",
         a3: "Kelelawar",
         f3: "Laba-laba",
         q3: "Satu-satunya mamalia yang terbang dan sering mengandalkan ekolokasi adalah...",
         a4: "Capung",
         f4: "Kupu-kupu",
         q4: "Serangga dengan tingkat keberhasilan berburu tertinggi (sekitar 95%) adalah..."
      },
      55: {
         a1: "Nyamuk",
         f1: "Lalat Tse Tse",
         q1: "Serangga yang menyebabkan penyakit mematikan terbanyak di seluruh dunia adalah...",
         a2: "Hidung",
         f2: "Telinga",
         q2: "Organ manusia yang terus memanjang akibat gravitasi dan pertumbuhan tulang rawan (selain telinga) adalah...",
         a3: "Otak",
         f3: "Jantung",
         q3: "Organ tubuh yang menggunakan sekitar 20% dari total energi tubuh manusia meskipun beratnya hanya 2% adalah...",
         a4: "Kuda Laut",
         f4: "Ikan Badut",
         q4: "Satu-satunya hewan laut di mana sang jantan bertugas membawa telur dan melahirkan adalah..."
      },
      56: {
         a1: "Kuku",
         f1: "Rambut",
         q1: "Bagian tubuh manusia yang terbuat dari bahan yang sama dengan cula badak adalah...",
         a2: "Rumput",
         f2: "Bambu",
         q2: "Pohon pisang sebenarnya secara botani tidak diklasifikasikan sebagai pohon, melainkan keluarga dari tumbuhan...",
         a3: "Garam",
         f3: "Gula",
         q3: "Bumbu dapur yang pada zaman Romawi Kuno digunakan sebagai pembayaran tentara (asal mula kata salary) adalah...",
         a4: "Unta",
         f4: "Kuda Liar",
         q4: "Hewan gurun yang tidak menyimpan air di punuknya, melainkan menyimpan cadangan lemak adalah..."
      },
      57: {
         a1: "Alpukat",
         f1: "Pisang",
         q1: "Buah ini sangat beracun bagi burung peliharaan, kuda, dan hewan lainnya karena zat persin:",
         a2: "Paus Biru",
         f2: "Hiu Paus",
         q2: "Hewan mamalia ini memiliki suara paling keras dari seluruh hewan di dunia (bisa mencapai 188 desibel):",
         a3: "Platypus",
         f3: "Kanguru",
         q3: "Hewan unik asal Australia ini sama sekali tidak memiliki perut (lambung) dalam sistem pencernaannya:",
         a4: "Lobster",
         f4: "Kepiting",
         q4: "Hewan laut bercangkang yang darahnya berwarna biru jernih karena mengandung tembaga (hemosianin) adalah..."
      },
      58: {
         a1: "Madu",
         f1: "Gula Merah",
         q1: "Pemanis kuno yang ditemukan utuh di dalam makam Firaun Mesir kuno dan masih bisa dimakan karena tidak bisa basi:",
         a2: "Koala",
         f2: "Kungkang",
         q2: "Hewan yang sidik jarinya sangat identik dengan sidik jari manusia, bahkan sulit dibedakan dengan mikroskop:",
         a3: "Kadal",
         f3: "Ular",
         q3: "Reptil yang bisa dengan sengaja melepaskan ekornya untuk mengelabui pemangsa adalah...",
         a4: "Kucing",
         f4: "Anjing",
         q4: "Satu-satunya hewan peliharaan mamalia yang genetikanya tidak memiliki reseptor untuk mengecap rasa manis:"
      },
      59: {
         a1: "Paus Sperma",
         f1: "Hiu Putih",
         q1: "Hewan predator laut dalam ini memiliki ukuran otak terbesar dari semua makhluk yang pernah ada di Bumi:",
         a2: "Air Mata",
         f2: "Keringat",
         q2: "Cairan tubuh ini memiliki bentuk kristal yang berbeda-beda jika dilihat di mikroskop, tergantung apakah kita sedih atau bahagia:",
         a3: "Siput",
         f3: "Cacing Tanah",
         q3: "Hewan moluska lambat ini dapat berhibernasi (tidur panjang) hingga tiga tahun penuh:",
         a4: "Gajah",
         f4: "Kuda Nil",
         q4: "Satu-satunya mamalia besar di darat yang sama sekali tidak dapat melompat karena berat tubuhnya:"
      },
      60: {
         a1: "Tarantula",
         f1: "Ular Kobra",
         q1: "Laba-laba besar yang bisa bertahan hidup tanpa makanan lebih dari dua tahun berturut-turut adalah...",
         a2: "Otak",
         f2: "Jantung",
         q2: "Organ tubuh yang tidak memiliki reseptor rasa sakit, sehingga operasi bedah bisa dilakukan saat pasien terbangun:",
         a3: "Emas",
         f3: "Platinum",
         q3: "Total jumlah logam ini yang pernah ditambang manusia diperkirakan bisa muat ke dalam tiga kolam renang Olimpiade:",
         a4: "Cumi-cumi",
         f4: "Gurita",
         q4: "Hewan cerdas ini otak utamanya berbentuk seperti donat yang melingkari saluran pencernaannya (kerongkongan):"
      },
      61: {
         a1: "100 Tahun",
         f1: "Infinity War",
         q1: "Perang antara Inggris dan Prancis yang berlangsung selama lebih dari seabad dikenal sebagai Perang...",
         a2: "Inca",
         f2: "Maya",
         q2: "Kekaisaran besar di Amerika Selatan yang ditaklukkan oleh penjelajah Spanyol Francisco Pizarro adalah...",
         a3: "Augustus",
         f3: "Julius Caesar",
         q3: "Siapakah kaisar Romawi yang pertama?",
         a4: "Inca",
         f4: "Aztec",
         q4: "Peradaban kuno yang membangun kota spektakuler Machu Picchu di pegunungan Andes adalah..."
      },
      62: {
         a1: "Avatar",
         f1: "Avengers: Endgame",
         q1: "Film fiksi ilmiah dengan pendapatan tertinggi sepanjang masa (tanpa penyesuaian inflasi) adalah...",
         a2: "Robert Downey Jr.",
         f2: "Chris Evans",
         q2: "Siapakah aktor yang sukses memerankan karakter Iron Man di Marvel Cinematic Universe?",
         a3: "Toy Story",
         f3: "Shrek",
         q3: "Film animasi pemenang Oscar (1995) yang menjadi film panjang pertama dengan efek CGI sepenuhnya adalah...",
         a4: "Merah",
         f4: "Biru",
         q4: "Dalam film ikonik \"The Matrix\", pil warna apa yang dipilih oleh Neo untuk mengetahui kebenaran?"
      },
      63: {
         a1: "Paulus",
         f1: "Petrus",
         q1: "Di dalam Alkitab, siapakah rasul yang menulis paling banyak kitab/surat dalam Perjanjian Baru?",
         a2: "Yordan",
         f2: "Nil",
         q2: "Sungai tempat Yesus Kristus dibaptis oleh Yohanes Pembaptis adalah sungai...",
         a3: "Salomo",
         f3: "Daud",
         q3: "Siapakah raja Israel yang terkenal paling bijaksana dan yang membangun Bait Allah pertama di Yerusalem?",
         a4: "Merpati",
         f4: "Gagak",
         q4: "Burung apa yang dilepaskan Nuh dan kembali membawa ranting zaitun setelah air bah surut?"
      },
      64: {
         a1: "Kutu",
         f1: "Nyamuk",
         q1: "Dalam sejarah dunia, wabah mematikan \"Black Death\" (Maut Hitam) disebarkan oleh hewan parasit yaitu...",
         a2: "James Cameron",
         f2: "Steven Spielberg",
         q2: "Film \"Titanic\" (1997) memenangkan 11 piala Oscar. Siapakah sutradara di balik film ini?",
         a3: "Getsemani",
         f3: "Eden",
         q3: "Menurut catatan Alkitab, di taman manakah Yesus berdoa dengan sangat sedih sebelum Dia ditangkap?",
         a4: "Napoleon Bonaparte",
         f4: "Louis XIV",
         q4: "Kaisar dan jenderal besar Prancis yang akhirnya kalah telak dalam pertempuran Waterloo adalah..."
      },
      65: {
         a1: "Tom Hanks",
         f1: "Brad Pitt",
         q1: "Pemeran utama film \"Forrest Gump\" yang memenangkan piala Oscar untuk Aktor Terbaik adalah...",
         a2: "Kain",
         f2: "Lamekh",
         q2: "Berdasarkan kitab Kejadian, siapakah manusia pertama yang melakukan pembunuhan terhadap saudaranya?",
         a3: "1989",
         f3: "1991",
         q3: "Tembok Berlin yang menjadi simbol utama Perang Dingin akhirnya diruntuhkan pada tahun...",
         a4: "Star Wars",
         f4: "Star Trek",
         q4: "Waralaba film epik mana yang menampilkan tokoh antagonis ikonik bernama Darth Vader?"
      },
      66: {
         a1: "Yunus",
         f1: "Ayub",
         q1: "Nabi manakah yang ditelan oleh ikan besar karena berusaha melarikan diri dari perintah Tuhan menuju Niniwe?",
         a2: "Thomas Alva Edison",
         f2: "Nikola Tesla",
         q2: "Siapakah tokoh penemu yang memegang lebih dari 1.000 paten dan sering dikreditkan sebagai penemu bola lampu praktis?",
         a3: "Stephen King",
         f3: "Edgar Allan Poe",
         q3: "Film horor klasik \"The Shining\" (1980) diadaptasi dari novel horor karya penulis terkenal bernama...",
         a4: "Sinai",
         f4: "Ararat",
         q4: "Di gunung manakah Nabi Musa menerima loh batu berisi Sepuluh Perintah Allah?"
      },
      67: {
         a1: "Ian Fleming",
         f1: "Arthur Conan Doyle",
         q1: "Karakter agen rahasia asal Inggris bernama James Bond (007) diciptakan oleh penulis fiksi...",
         a2: "Cleopatra",
         f2: "Nefertiti",
         q2: "Siapakah Ratu Mesir kuno terakhir yang memiliki hubungan romantis dan politik dengan Julius Caesar?",
         a3: "Esau",
         f3: "Yakub",
         q3: "Siapakah tokoh dalam Alkitab yang menjual hak kesulungannya sendiri hanya demi semangkuk sup merah?",
         a4: "Steven Spielberg",
         f4: "Christopher Nolan",
         q4: "Sutradara legendaris yang menggarap film \"Jurassic Park\" dan \"E.T. the Extra-Terrestrial\" adalah..."
      },
      68: {
         a1: "Hiroshima",
         f1: "Nagasaki",
         q1: "Kota di dunia yang pertama kali dijatuhi bom atom saat masa Perang Dunia II adalah kota...",
         a2: "Debora",
         f2: "Rut",
         q2: "Di Alkitab, siapakah hakim perempuan Israel yang biasa duduk dan bernubuat di bawah pohon kurma?",
         a3: "Christian Bale",
         f3: "Ben Affleck",
         q3: "Siapakah aktor yang memerankan pahlawan super Batman dengan sangat ikonik dalam trilogi \"The Dark Knight\"?",
         a4: "Inggris",
         f4: "Amerika Serikat",
         q4: "Revolusi Industri Pertama, yang mengubah cara manusia memproduksi barang, bermula dari negara mana?"
      },
      69: {
         a1: "Patmos",
         f1: "Siprus",
         q1: "Di manakah nama pulau tempat Rasul Yohanes diasingkan saat menerima penglihatan Kitab Wahyu?",
         a2: "Johnny Depp",
         f2: "Orlando Bloom",
         q2: "Aktor nyentrik yang sangat sukses memerankan bajak laut Kapten Jack Sparrow adalah...",
         a3: "Nelson Mandela",
         f3: "Martin Luther King Jr.",
         q3: "Tokoh perdamaian sejarah yang mengakhiri sistem apartheid dan menjadi presiden kulit hitam pertama Afrika Selatan:",
         a4: "Keledai",
         f4: "Unta",
         q4: "Berdasarkan Alkitab (Kitab Bilangan), hewan apakah yang bisa berbicara saat dihentikan oleh Malaikat Tuhan?"
      },
      70: {
         a1: "J.R.R. Tolkien",
         f1: "J.K. Rowling",
         q1: "Trilogi film pemenang Oscar \"The Lord of the Rings\" diadaptasi dari buku fantasi epik karya penulis...",
         a2: "Titanic",
         f2: "Lusitania",
         q2: "Apa nama kapal pesiar super mewah yang tenggelam setelah menabrak gunung es pada pelayaran perdananya di tahun 1912?",
         a3: "Petrus",
         f3: "Yudas Iskariot",
         q3: "Murid Yesus manakah yang menyangkal-Nya sebanyak tiga kali sebelum ayam berkokok?",
         a4: "Christopher Columbus",
         f4: "Vasco da Gama",
         q4: "Penjelajah dunia yang mendarat pada tahun 1492 dan dipercaya (oleh sejarah Eropa) menemukan benua Amerika adalah..."
      }
   }
};

var configName = typeof (process.env.NODE_ENV) == 'string' ? process.env.NODE_ENV : 'sean';
var selectedConfig = typeof (config[configName]) == 'object' ? config[configName] : config.local;
module.exports = selectedConfig;